from __future__ import annotations

from sqlalchemy.orm import Session

from app.models.enums import DriveMode, ImplementType, TireType
from app.models.implement import Implement
from app.models.tire_specification import TireSpecification
from app.models.tractor import Tractor


def seed_library_if_empty(db: Session) -> None:
    """
    Seed a comprehensive library of tractors and implements for the UI.

    This does NOT touch simulation algorithms; it only inserts default reference data.
    """
    has_library_tractors = db.query(Tractor).filter(Tractor.is_library == True).first()  # noqa: E712
    has_library_implements = db.query(Implement).filter(Implement.is_library == True).first()  # noqa: E712

    if has_library_tractors and has_library_implements:
        return

    if not has_library_tractors:
        # Tractors data
        tractors_data = [
            {
                "name": "Captain DI 2600",
                "manufacturer": "Captain",
                "model": "DI 2600",
                "pto_power": 6.6,
                "rated_engine_speed": 2600,
                "max_engine_torque": 25,
                "wheelbase": 1.705,
                "front_axle_weight": 375,
                "rear_axle_weight": 605,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 0.89,
                "rear_wheel_rolling_radius": 0.22,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 355,
                    "front_section_width": 132,
                    "front_static_loaded_radius": 168,
                    "front_rolling_radius": 172,
                    "rear_overall_diameter": 457,
                    "rear_section_width": 203,
                    "rear_static_loaded_radius": 217,
                    "rear_rolling_radius": 221,
                },
            },
            {
                "name": "Mitsubishi MT 180 D",
                "manufacturer": "Mitsubishi",
                "model": "MT 180 D",
                "pto_power": 12,
                "rated_engine_speed": 2700,
                "max_engine_torque": 45.5,
                "wheelbase": 1.42,
                "front_axle_weight": 315,
                "rear_axle_weight": 440,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 0.74,
                "rear_wheel_rolling_radius": 0.22,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 304,
                    "front_section_width": 127,
                    "front_static_loaded_radius": 144,
                    "front_rolling_radius": 147,
                    "rear_overall_diameter": 457,
                    "rear_section_width": 203,
                    "rear_static_loaded_radius": 217,
                    "rear_rolling_radius": 221,
                },
            },
            {
                "name": "Eicher 242 NC",
                "manufacturer": "Eicher",
                "model": "242 NC",
                "pto_power": 14.8,
                "rated_engine_speed": 1650,
                "max_engine_torque": 96.9,
                "wheelbase": 1.881,
                "front_axle_weight": 680,
                "rear_axle_weight": 1070,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 0.98,
                "rear_wheel_rolling_radius": 0.34,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 406,
                    "front_section_width": 152,
                    "front_static_loaded_radius": 192,
                    "front_rolling_radius": 196,
                    "rear_overall_diameter": 711,
                    "rear_section_width": 314,
                    "rear_static_loaded_radius": 337,
                    "rear_rolling_radius": 344,
                },
            },
            {
                "name": "Eicher 243 NC",
                "manufacturer": "Eicher",
                "model": "243 NC",
                "pto_power": 14.4,
                "rated_engine_speed": 1650,
                "max_engine_torque": 91.3,
                "wheelbase": 1.87,
                "front_axle_weight": 655,
                "rear_axle_weight": 1080,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 0.97,
                "rear_wheel_rolling_radius": 0.34,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 406,
                    "front_section_width": 152,
                    "front_static_loaded_radius": 192,
                    "front_rolling_radius": 196,
                    "rear_overall_diameter": 711,
                    "rear_section_width": 314,
                    "rear_static_loaded_radius": 337,
                    "rear_rolling_radius": 344,
                },
            },
            {
                "name": "Eicher 312 NC",
                "manufacturer": "Eicher",
                "model": "312 NC",
                "pto_power": 20.7,
                "rated_engine_speed": 2150,
                "max_engine_torque": 93.1,
                "wheelbase": 1.888,
                "front_axle_weight": 645,
                "rear_axle_weight": 1090,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 0.98,
                "rear_wheel_rolling_radius": 0.34,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 406,
                    "front_section_width": 152,
                    "front_static_loaded_radius": 192,
                    "front_rolling_radius": 196,
                    "rear_overall_diameter": 711,
                    "rear_section_width": 314,
                    "rear_static_loaded_radius": 337,
                    "rear_rolling_radius": 344,
                },
            },
            {
                "name": "Eicher 364 P",
                "manufacturer": "Eicher",
                "model": "364 P",
                "pto_power": 22.7,
                "rated_engine_speed": 2150,
                "max_engine_torque": 117,
                "wheelbase": 1.9,
                "front_axle_weight": 645,
                "rear_axle_weight": 1235,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 0.99,
                "rear_wheel_rolling_radius": 0.34,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 406,
                    "front_section_width": 152,
                    "front_static_loaded_radius": 192,
                    "front_rolling_radius": 196,
                    "rear_overall_diameter": 711,
                    "rear_section_width": 314,
                    "rear_static_loaded_radius": 337,
                    "rear_rolling_radius": 344,
                },
            },
            {
                "name": "Eicher 368",
                "manufacturer": "Eicher",
                "model": "368",
                "pto_power": 25,
                "rated_engine_speed": 2150,
                "max_engine_torque": 132.5,
                "wheelbase": 1.985,
                "front_axle_weight": 720,
                "rear_axle_weight": 1100,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 1.03,
                "rear_wheel_rolling_radius": 0.34,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 406,
                    "front_section_width": 152,
                    "front_static_loaded_radius": 192,
                    "front_rolling_radius": 196,
                    "rear_overall_diameter": 711,
                    "rear_section_width": 314,
                    "rear_static_loaded_radius": 337,
                    "rear_rolling_radius": 344,
                },
            },
            {
                "name": "Eicher 485",
                "manufacturer": "Eicher",
                "model": "485",
                "pto_power": 28.7,
                "rated_engine_speed": 2150,
                "max_engine_torque": 148.7,
                "wheelbase": 2.07,
                "front_axle_weight": 695,
                "rear_axle_weight": 1205,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 1.08,
                "rear_wheel_rolling_radius": 0.34,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 406,
                    "front_section_width": 152,
                    "front_static_loaded_radius": 192,
                    "front_rolling_radius": 196,
                    "rear_overall_diameter": 711,
                    "rear_section_width": 314,
                    "rear_static_loaded_radius": 337,
                    "rear_rolling_radius": 344,
                },
            },
            {
                "name": "Eicher 586",
                "manufacturer": "Eicher",
                "model": "586",
                "pto_power": 33.9,
                "rated_engine_speed": 2150,
                "max_engine_torque": 179.6,
                "wheelbase": 2.095,
                "front_axle_weight": 825,
                "rear_axle_weight": 1485,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 1.09,
                "rear_wheel_rolling_radius": 0.34,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 406,
                    "front_section_width": 152,
                    "front_static_loaded_radius": 192,
                    "front_rolling_radius": 196,
                    "rear_overall_diameter": 711,
                    "rear_section_width": 345,
                    "rear_static_loaded_radius": 337,
                    "rear_rolling_radius": 344,
                },
            },
            {
                "name": "Eicher 6100",
                "manufacturer": "Eicher",
                "model": "6100",
                "pto_power": 40.2,
                "rated_engine_speed": 1250,
                "max_engine_torque": 207.9,
                "wheelbase": 2.115,
                "front_axle_weight": 1315,
                "rear_axle_weight": 1550,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 1.1,
                "rear_wheel_rolling_radius": 0.37,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 406,
                    "front_section_width": 190,
                    "front_static_loaded_radius": 192,
                    "front_rolling_radius": 196,
                    "rear_overall_diameter": 762,
                    "rear_section_width": 429,
                    "rear_static_loaded_radius": 361,
                    "rear_rolling_radius": 369,
                },
            },
            {
                "name": "Mahindra & Mahindra 2515 DI",
                "manufacturer": "Mahindra & Mahindra",
                "model": "2515 DI",
                "pto_power": 17.2,
                "rated_engine_speed": 2600,
                "max_engine_torque": 70.4,
                "wheelbase": 1.746,
                "front_axle_weight": 655,
                "rear_axle_weight": 875,
                "hitch_distance_from_rear": 0.72,
                "cg_distance_from_rear": 0.91,
                "rear_wheel_rolling_radius": 0.29,
                "tire": {
                    "tire_type": TireType.BIAS_PLY,
                    "front_overall_diameter": 381,
                    "front_section_width": 127,
                    "front_static_loaded_radius": 180,
                    "front_rolling_radius": 184,
                    "rear_overall_diameter": 609,
                    "rear_section_width": 314,
                    "rear_static_loaded_radius": 289,
                    "rear_rolling_radius": 295,
                },
            },
        ]

        # Add all tractors
        for tractor_data in tractors_data:
            tire_data = tractor_data.pop("tire", None)
            tractor = Tractor(
                **tractor_data,
                drive_mode=DriveMode.WD2,
                transmission_efficiency=86.0,
                power_reserve=20.0,
                is_library=True,
            )
            db.add(tractor)
            db.flush()

            # Add tire specification if provided
            if tire_data:
                db.add(TireSpecification(tractor_id=tractor.id, **tire_data))

    if not has_library_implements:
        # Implements data
        implements_data = [
            {
                "name": "2-Bottom MB Plough",
                "manufacturer": "Standard",
                "implement_type": ImplementType.MB_PLOUGH,
                "width": 0.6,
                "weight": 280,
                "cg_distance_from_hitch": 0.4,
                "vertical_horizontal_ratio": 0.65,
                "asae_param_a": 500,
                "asae_param_b": 50,
                "asae_param_c": 8,
            },
            {
                "name": "3-Bottom MB Plough",
                "manufacturer": "Standard",
                "implement_type": ImplementType.MB_PLOUGH,
                "width": 0.9,
                "weight": 380,
                "cg_distance_from_hitch": 0.45,
                "vertical_horizontal_ratio": 0.65,
                "asae_param_a": 500,
                "asae_param_b": 50,
                "asae_param_c": 8,
            },
            {
                "name": "4-Bottom MB Plough",
                "manufacturer": "Standard",
                "implement_type": ImplementType.MB_PLOUGH,
                "width": 1.2,
                "weight": 500,
                "cg_distance_from_hitch": 0.5,
                "vertical_horizontal_ratio": 0.65,
                "asae_param_a": 500,
                "asae_param_b": 50,
                "asae_param_c": 8,
            },
            {
                "name": "5-Bottom MB Plough",
                "manufacturer": "Heavy Duty",
                "implement_type": ImplementType.MB_PLOUGH,
                "width": 1.5,
                "weight": 620,
                "cg_distance_from_hitch": 0.55,
                "vertical_horizontal_ratio": 0.65,
                "asae_param_a": 500,
                "asae_param_b": 50,
                "asae_param_c": 8,
            },
            {
                "name": "2-Disc Plough",
                "manufacturer": "Standard",
                "implement_type": ImplementType.DISC_PLOUGH,
                "width": 0.8,
                "weight": 320,
                "cg_distance_from_hitch": 0.42,
                "vertical_horizontal_ratio": 0.6,
                "asae_param_a": 400,
                "asae_param_b": 45,
                "asae_param_c": 7,
            },
            {
                "name": "3-Disc Plough",
                "manufacturer": "Standard",
                "implement_type": ImplementType.DISC_PLOUGH,
                "width": 1.2,
                "weight": 450,
                "cg_distance_from_hitch": 0.48,
                "vertical_horizontal_ratio": 0.6,
                "asae_param_a": 400,
                "asae_param_b": 45,
                "asae_param_c": 7,
            },
            {
                "name": "4-Disc Plough",
                "manufacturer": "Heavy Duty",
                "implement_type": ImplementType.DISC_PLOUGH,
                "width": 1.6,
                "weight": 580,
                "cg_distance_from_hitch": 0.52,
                "vertical_horizontal_ratio": 0.6,
                "asae_param_a": 400,
                "asae_param_b": 45,
                "asae_param_c": 7,
            },
            {
                "name": "Light Cultivator (9 Tines)",
                "manufacturer": "Standard",
                "implement_type": ImplementType.CULTIVATOR,
                "width": 1.2,
                "weight": 180,
                "cg_distance_from_hitch": 0.35,
                "vertical_horizontal_ratio": 0.55,
                "asae_param_a": 200,
                "asae_param_b": 30,
                "asae_param_c": 5,
            },
            {
                "name": "Medium Cultivator (13 Tines)",
                "manufacturer": "Standard",
                "implement_type": ImplementType.CULTIVATOR,
                "width": 1.8,
                "weight": 280,
                "cg_distance_from_hitch": 0.4,
                "vertical_horizontal_ratio": 0.55,
                "asae_param_a": 200,
                "asae_param_b": 30,
                "asae_param_c": 5,
            },
            {
                "name": "Heavy Cultivator (17 Tines)",
                "manufacturer": "Heavy Duty",
                "implement_type": ImplementType.CULTIVATOR,
                "width": 2.4,
                "weight": 420,
                "cg_distance_from_hitch": 0.48,
                "vertical_horizontal_ratio": 0.55,
                "asae_param_a": 200,
                "asae_param_b": 30,
                "asae_param_c": 5,
            },
            {
                "name": "Light Disc Harrow (16 Discs)",
                "manufacturer": "Standard",
                "implement_type": ImplementType.DISC_HARROW,
                "width": 1.5,
                "weight": 220,
                "cg_distance_from_hitch": 0.38,
                "vertical_horizontal_ratio": 0.5,
                "asae_param_a": 150,
                "asae_param_b": 25,
                "asae_param_c": 4,
            },
            {
                "name": "Medium Disc Harrow (24 Discs)",
                "manufacturer": "Standard",
                "implement_type": ImplementType.DISC_HARROW,
                "width": 2,
                "weight": 340,
                "cg_distance_from_hitch": 0.42,
                "vertical_horizontal_ratio": 0.5,
                "asae_param_a": 150,
                "asae_param_b": 25,
                "asae_param_c": 4,
            },
            {
                "name": "Heavy Disc Harrow (32 Discs)",
                "manufacturer": "Heavy Duty",
                "implement_type": ImplementType.DISC_HARROW,
                "width": 2.8,
                "weight": 520,
                "cg_distance_from_hitch": 0.5,
                "vertical_horizontal_ratio": 0.5,
                "asae_param_a": 150,
                "asae_param_b": 25,
                "asae_param_c": 4,
            },
        ]

        # Add all implements
        for implement_data in implements_data:
            implement = Implement(**implement_data, is_library=True)
            db.add(implement)

    db.commit()

