"""create initial tables

Revision ID: 06fb74fa2fc4
Revises: 
Create Date: 2026-03-02 16:37:29.592245

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fb74fa2fc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implements',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('implement_type', sa.Enum('MB_PLOUGH', 'DISC_PLOUGH', 'CULTIVATOR', 'DISC_HARROW', name='implement_type'), nullable=False),
    sa.Column('width', sa.DECIMAL(), nullable=True),
    sa.Column('weight', sa.DECIMAL(), nullable=True),
    sa.Column('cg_distance_from_hitch', sa.DECIMAL(), nullable=True),
    sa.Column('vertical_horizontal_ratio', sa.DECIMAL(), nullable=True),
    sa.Column('asae_param_a', sa.DECIMAL(), nullable=True),
    sa.Column('asae_param_b', sa.DECIMAL(), nullable=True),
    sa.Column('asae_param_c', sa.DECIMAL(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implements_implement_type'), 'implements', ['implement_type'], unique=False)
    op.create_index(op.f('ix_implements_manufacturer'), 'implements', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_implements_name'), 'implements', ['name'], unique=False)
    op.create_table('operating_conditions_presets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('soil_texture', sa.Enum('FINE', 'COARSE', 'MEDIUM', name='soil_texture'), nullable=False),
    sa.Column('soil_hardness', sa.Enum('HARD', 'FIRM', 'TILLED', 'SOFT', name='soil_hardness'), nullable=False),
    sa.Column('cone_index', sa.DECIMAL(), nullable=True),
    sa.Column('depth', sa.DECIMAL(), nullable=True),
    sa.Column('speed', sa.DECIMAL(), nullable=True),
    sa.Column('field_area', sa.DECIMAL(), nullable=True),
    sa.Column('field_length', sa.DECIMAL(), nullable=True),
    sa.Column('field_width', sa.DECIMAL(), nullable=True),
    sa.Column('number_of_turns', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_conditions_presets_name'), 'operating_conditions_presets', ['name'], unique=False)
    op.create_index(op.f('ix_operating_conditions_presets_soil_hardness'), 'operating_conditions_presets', ['soil_hardness'], unique=False)
    op.create_index(op.f('ix_operating_conditions_presets_soil_texture'), 'operating_conditions_presets', ['soil_texture'], unique=False)
    op.create_table('tractors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('pto_power', sa.DECIMAL(), nullable=True),
    sa.Column('rated_engine_speed', sa.Integer(), nullable=True),
    sa.Column('max_engine_torque', sa.DECIMAL(), nullable=True),
    sa.Column('wheelbase', sa.DECIMAL(), nullable=True),
    sa.Column('front_axle_weight', sa.DECIMAL(), nullable=True),
    sa.Column('rear_axle_weight', sa.DECIMAL(), nullable=True),
    sa.Column('hitch_distance_from_rear', sa.DECIMAL(), nullable=True),
    sa.Column('cg_distance_from_rear', sa.DECIMAL(), nullable=True),
    sa.Column('rear_wheel_rolling_radius', sa.DECIMAL(), nullable=True),
    sa.Column('drive_mode', sa.Enum('WD2', 'WD4', name='drive_mode'), nullable=False),
    sa.Column('transmission_efficiency', sa.DECIMAL(), nullable=True),
    sa.Column('power_reserve', sa.DECIMAL(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tractors_drive_mode'), 'tractors', ['drive_mode'], unique=False)
    op.create_index(op.f('ix_tractors_manufacturer'), 'tractors', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_tractors_model'), 'tractors', ['model'], unique=False)
    op.create_index(op.f('ix_tractors_name'), 'tractors', ['name'], unique=False)
    op.create_table('simulations',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tractor_id', sa.Uuid(), nullable=False),
    sa.Column('implement_id', sa.Uuid(), nullable=False),
    sa.Column('operating_conditions_preset_id', sa.Uuid(), nullable=True),
    sa.Column('cone_index', sa.DECIMAL(), nullable=True),
    sa.Column('depth', sa.DECIMAL(), nullable=True),
    sa.Column('speed', sa.DECIMAL(), nullable=True),
    sa.Column('field_area', sa.DECIMAL(), nullable=True),
    sa.Column('field_length', sa.DECIMAL(), nullable=True),
    sa.Column('field_width', sa.DECIMAL(), nullable=True),
    sa.Column('number_of_turns', sa.Integer(), nullable=True),
    sa.Column('soil_texture', sa.String(), nullable=True),
    sa.Column('soil_hardness', sa.String(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('draft_force', sa.DECIMAL(), nullable=True),
    sa.Column('drawbar_power', sa.DECIMAL(), nullable=True),
    sa.Column('slip', sa.DECIMAL(), nullable=True),
    sa.Column('traction_efficiency', sa.DECIMAL(), nullable=True),
    sa.Column('power_utilization', sa.DECIMAL(), nullable=True),
    sa.Column('field_capacity_theoretical', sa.DECIMAL(), nullable=True),
    sa.Column('field_capacity_actual', sa.DECIMAL(), nullable=True),
    sa.Column('field_efficiency', sa.DECIMAL(), nullable=True),
    sa.Column('fuel_consumption_per_hectare', sa.DECIMAL(), nullable=True),
    sa.Column('overall_efficiency', sa.DECIMAL(), nullable=True),
    sa.Column('ballast_front_required', sa.DECIMAL(), nullable=True),
    sa.Column('ballast_rear_required', sa.DECIMAL(), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['implement_id'], ['implements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operating_conditions_preset_id'], ['operating_conditions_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_implement_id'), 'simulations', ['implement_id'], unique=False)
    op.create_index(op.f('ix_simulations_name'), 'simulations', ['name'], unique=False)
    op.create_index(op.f('ix_simulations_operating_conditions_preset_id'), 'simulations', ['operating_conditions_preset_id'], unique=False)
    op.create_index(op.f('ix_simulations_tractor_id'), 'simulations', ['tractor_id'], unique=False)
    op.create_table('tire_specifications',
    sa.Column('tractor_id', sa.Uuid(), nullable=False),
    sa.Column('tire_type', sa.Enum('BIAS_PLY', 'RADIAL_PLY', name='tire_type'), nullable=False),
    sa.Column('front_overall_diameter', sa.Integer(), nullable=True),
    sa.Column('front_section_width', sa.Integer(), nullable=True),
    sa.Column('front_static_loaded_radius', sa.Integer(), nullable=True),
    sa.Column('front_rolling_radius', sa.Integer(), nullable=True),
    sa.Column('rear_overall_diameter', sa.Integer(), nullable=True),
    sa.Column('rear_section_width', sa.Integer(), nullable=True),
    sa.Column('rear_static_loaded_radius', sa.Integer(), nullable=True),
    sa.Column('rear_rolling_radius', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tractor_id'], ['tractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tire_specifications_tractor_id'), 'tire_specifications', ['tractor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tire_specifications_tractor_id'), table_name='tire_specifications')
    op.drop_table('tire_specifications')
    op.drop_index(op.f('ix_simulations_tractor_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_operating_conditions_preset_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_name'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_implement_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_tractors_name'), table_name='tractors')
    op.drop_index(op.f('ix_tractors_model'), table_name='tractors')
    op.drop_index(op.f('ix_tractors_manufacturer'), table_name='tractors')
    op.drop_index(op.f('ix_tractors_drive_mode'), table_name='tractors')
    op.drop_table('tractors')
    op.drop_index(op.f('ix_operating_conditions_presets_soil_texture'), table_name='operating_conditions_presets')
    op.drop_index(op.f('ix_operating_conditions_presets_soil_hardness'), table_name='operating_conditions_presets')
    op.drop_index(op.f('ix_operating_conditions_presets_name'), table_name='operating_conditions_presets')
    op.drop_table('operating_conditions_presets')
    op.drop_index(op.f('ix_implements_name'), table_name='implements')
    op.drop_index(op.f('ix_implements_manufacturer'), table_name='implements')
    op.drop_index(op.f('ix_implements_implement_type'), table_name='implements')
    op.drop_table('implements')
    # ### end Alembic commands ###

